# Designing on page google calender

import csv

path = "Calendar.csv"
output = open(path, "w")
writer = csv.writer(output, delimiter=",")
writer.writerow(["date", "day of week", "things to do"])
writer.writerow(["1", "Monday", ""])
writer.writerow(["2",  "Tuesday", ""])
writer.writerow(["3", "Wednesday", ""])
writer.writerow(["4",  "Thursday", ""])
writer.writerow(["5", "Friday", ""])
writer.writerow(["6", "Saturday", ""])
writer.writerow(["7", "Sunday", ""])
writer.writerow(["8", "Monday", ""])
writer.writerow(["9",  "Tuesday", ""])
writer.writerow(["10", "Wednesday", ""])
writer.writerow(["11",  "Thursday", ""])
writer.writerow(["12", "Friday", ""])
writer.writerow(["13", "Saturday", ""])
writer.writerow(["14", "Sunday", ""])
writer.writerow(["15", "Monday", ""])
writer.writerow(["16",  "Tuesday", ""])
writer.writerow(["17", "Wednesday", ""])
writer.writerow(["18",  "Thursday", ""])
writer.writerow(["19", "Friday", ""])
writer.writerow(["20", "Saturday", ""])
writer.writerow(["21", "Sunday", ""])
writer.writerow(["22", "Monday", ""])
writer.writerow(["23",  "Tuesday", ""])
writer.writerow(["24", "Wednesday", ""])
writer.writerow(["25",  "Thursday", ""])
writer.writerow(["26", "Friday", ""])
writer.writerow(["27", "Saturday", ""])
writer.writerow(["28", "Sunday", ""])
writer.writerow(["29", "Monday", ""])
writer.writerow(["30",  "Tuesday", ""])
writer.writerow(["31", "Wednesday", ""])
